
language: php
addons:
  postgresql: "9.4"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
 matrix:
  - DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_33_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
  - DB=pgsql MOODLE_BRANCH=master
  - DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
  - DB=mysqli MOODLE_BRANCH=master

matrix:
  exclude:
    - php: 5.6
      env: DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
    - php: 5.6
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 5.6
      env: DB=pgsql MOODLE_BRANCH=master
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=MOODLE_33_STABLE
    - php: 5.6
      env: DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
    - php: 5.6
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 5.6
      env: DB=mysqli MOODLE_BRANCH=master
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE

before_install:
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install -vvv
  - if [ "$MOODLE_BRANCH" == "MOODLE_31_STABLE" ]; then (cd moodle; composer require --dev --no-interaction --prefer-dist guzzlehttp/guzzle:~6.0 fabpot/goutte:~3); fi

before_script:
  - sleep 1

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci shifter
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat      # No tests yet

